FROM python:3.11-slim
WORKDIR /app
COPY police/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY police ./police
EXPOSE 8001
CMD ["python", "-m", "police.main"]
